/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as SejaUmAssociadoRouteImport } from './routes/seja-um-associado'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as PatologiasIndexRouteImport } from './routes/patologias.index'
import { Route as PatologiasSlugRouteImport } from './routes/patologias.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaUmAssociadoRoute = SejaUmAssociadoRouteImport.update({
  id: '/seja-um-associado',
  path: '/seja-um-associado',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PatologiasIndexRoute = PatologiasIndexRouteImport.update({
  id: '/patologias/',
  path: '/patologias/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatologiasSlugRoute = PatologiasSlugRouteImport.update({
  id: '/patologias/$slug',
  path: '/patologias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/institucional': typeof InstitucionalRoute
  '/profissionais': typeof ProfissionaisRoute
  '/seja-um-associado': typeof SejaUmAssociadoRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/patologias/$slug': typeof PatologiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/patologias/': typeof PatologiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/institucional': typeof InstitucionalRoute
  '/profissionais': typeof ProfissionaisRoute
  '/seja-um-associado': typeof SejaUmAssociadoRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/patologias/$slug': typeof PatologiasSlugRoute
  '/noticias': typeof NoticiasIndexRoute
  '/patologias': typeof PatologiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/institucional': typeof InstitucionalRoute
  '/profissionais': typeof ProfissionaisRoute
  '/seja-um-associado': typeof SejaUmAssociadoRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/patologias/$slug': typeof PatologiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/patologias/': typeof PatologiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/institucional'
    | '/profissionais'
    | '/seja-um-associado'
    | '/noticias/$slug'
    | '/patologias/$slug'
    | '/noticias/'
    | '/patologias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/institucional'
    | '/profissionais'
    | '/seja-um-associado'
    | '/noticias/$slug'
    | '/patologias/$slug'
    | '/noticias'
    | '/patologias'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/institucional'
    | '/profissionais'
    | '/seja-um-associado'
    | '/noticias/$slug'
    | '/patologias/$slug'
    | '/noticias/'
    | '/patologias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  InstitucionalRoute: typeof InstitucionalRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  SejaUmAssociadoRoute: typeof SejaUmAssociadoRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  PatologiasSlugRoute: typeof PatologiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  PatologiasIndexRoute: typeof PatologiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-um-associado': {
      id: '/seja-um-associado'
      path: '/seja-um-associado'
      fullPath: '/seja-um-associado'
      preLoaderRoute: typeof SejaUmAssociadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patologias/': {
      id: '/patologias/'
      path: '/patologias'
      fullPath: '/patologias/'
      preLoaderRoute: typeof PatologiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patologias/$slug': {
      id: '/patologias/$slug'
      path: '/patologias/$slug'
      fullPath: '/patologias/$slug'
      preLoaderRoute: typeof PatologiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  InstitucionalRoute: InstitucionalRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  SejaUmAssociadoRoute: SejaUmAssociadoRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  PatologiasSlugRoute: PatologiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  PatologiasIndexRoute: PatologiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
