/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PatologiasIndexRouteImport } from './routes/patologias.index'
import { Route as PatologiasSlugRouteImport } from './routes/patologias.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PatologiasIndexRoute = PatologiasIndexRouteImport.update({
  id: '/patologias/',
  path: '/patologias/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatologiasSlugRoute = PatologiasSlugRouteImport.update({
  id: '/patologias/$slug',
  path: '/patologias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/institucional': typeof InstitucionalRoute
  '/noticias': typeof NoticiasRoute
  '/profissionais': typeof ProfissionaisRoute
  '/patologias/$slug': typeof PatologiasSlugRoute
  '/patologias/': typeof PatologiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institucional': typeof InstitucionalRoute
  '/noticias': typeof NoticiasRoute
  '/profissionais': typeof ProfissionaisRoute
  '/patologias/$slug': typeof PatologiasSlugRoute
  '/patologias': typeof PatologiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/institucional': typeof InstitucionalRoute
  '/noticias': typeof NoticiasRoute
  '/profissionais': typeof ProfissionaisRoute
  '/patologias/$slug': typeof PatologiasSlugRoute
  '/patologias/': typeof PatologiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/institucional'
    | '/noticias'
    | '/profissionais'
    | '/patologias/$slug'
    | '/patologias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/institucional'
    | '/noticias'
    | '/profissionais'
    | '/patologias/$slug'
    | '/patologias'
  id:
    | '__root__'
    | '/'
    | '/institucional'
    | '/noticias'
    | '/profissionais'
    | '/patologias/$slug'
    | '/patologias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstitucionalRoute: typeof InstitucionalRoute
  NoticiasRoute: typeof NoticiasRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  PatologiasSlugRoute: typeof PatologiasSlugRoute
  PatologiasIndexRoute: typeof PatologiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patologias/': {
      id: '/patologias/'
      path: '/patologias'
      fullPath: '/patologias/'
      preLoaderRoute: typeof PatologiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patologias/$slug': {
      id: '/patologias/$slug'
      path: '/patologias/$slug'
      fullPath: '/patologias/$slug'
      preLoaderRoute: typeof PatologiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstitucionalRoute: InstitucionalRoute,
  NoticiasRoute: NoticiasRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  PatologiasSlugRoute: PatologiasSlugRoute,
  PatologiasIndexRoute: PatologiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
